# This workflow will build the Java project with Maven and create a Github release

name: Release
on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Release to Github
      uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        commit: main
        tag: ${{ github.sha }}
        draft: true
