# This workflow will build the Java project with Maven and create a Github release

name: Release
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn package
    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: maven-build-jar
        path: target/aerospike-circuit-breaker-*-with-dependencies.jar
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Download jar
      uses: actions/download-artifact@v4
      with:
        name: maven-build-jar
        path: target/aerospike-circuit-breaker-*-with-dependencies.jar
    - name: Release to Github
      uses: ncipollo/release-action@v1
      with:
        artifacts: "target/aerospike-circuit-breaker-*-with-dependencies.jar"
        generateReleaseNotes: true
        commit: main
        tag: ${{ github.sha }}
        draft: true
